# Generated by Django 3.0.4 on 2020-06-04 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200424_1537'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailconfirmed',
            options={'verbose_name_plural': 'Email Confirmed'},
        ),
    ]
