# Generated by Django 3.0.4 on 2020-06-12 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200612_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='address2',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='state',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
