# Generated by Django 3.0.4 on 2020-06-12 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200612_1239'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraddress',
            options={'verbose_name_plural': 'WebAm Shopping User Address'},
        ),
    ]
