# Generated by Django 3.0.4 on 2020-04-02 12:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20200331_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=uuid.uuid4, max_length=150, unique=True),
        ),
    ]
