# Generated by Django 3.0.4 on 2020-04-02 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20200402_1646'),
    ]

    operations = [
    ]
